version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    package_pip: 'ansible-core>=2.15,<2.16.99'
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: ansible.netcommon
        source: https://galaxy.ansible.com
        version: <5
      - name: ansible.posix
        source: https://galaxy.ansible.com
        version: <2
      - name: ansible.utils
        source: https://galaxy.ansible.com
        version: <5
      - name: community.crypto
        source: https://galaxy.ansible.com
        version: <3
      - name: community.general
        source: https://galaxy.ansible.com
        version: <7
      - name: community.docker
        source: https://galaxy.ansible.com
        version: <4
      - name: containers.podman
        source: https://galaxy.ansible.com
        version: <2
  system: |
    which [platform:rpm]
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    cmake [platform:rpm compile]
    gcc [platform:rpm compile]
    gcc-c++ [platform:rpm compile]
    make [platform:rpm compile]
    openssl-devel [platform:rpm compile]
    kmod [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    receptorctl
    git+https://opendev.org/openstack/kolla-ansible@stable/2024.1
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
    - RUN ln -sf /bin/bash /bin/sh
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
