version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: 'ansible-core>=2.15,<2.16.99'
  ansible_runner:
    package_pip: ansible-runner
  python:
    - git+https://opendev.org/openstack/kolla-ansible@stable/2024.1
  galaxy:
    collections:
      - name: ansible.utils

additional_build_steps:
  append_base:
    # Install git, bash, etc.
    - RUN dnf install -y git which bash
    - RUN ln -sf /bin/bash /bin/sh
  append_final:
    # Install kolla-ansible dependencies
    - RUN kolla-ansible install-deps
