name: Build Ansible Execution Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
           submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Upgrade pip and install ansible-builder
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder

      - name: Build Execution Environment
        run: ansible-builder build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/kolla-ansible-ee

      - name: Push Execution Environment Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kolla-ansible-ee:latest
